server:
 port: 8001

spring:
 application:
  name: services-product
 data:
  mongodb:
   uri: mongodb+srv://entrespanAdmin:6408hfcOvgKS2k4D@cluster0.0htyvdj.mongodb.net/db_products?retryWrites=true&w=majority